### ISSUE TITLE
Contact with multiple phone number

### ISSUE THREAD

**Issue by mgoku** [hazemhagrass/ContactPicker#5]
I use this plugin in Android 4.1.2 with Phonegap 3.3, and found this bugs.

When picking a contact who have more than 1 phone number (Mobile, Home, Work), no matter which one you pick, this plugin will always return Mobile  Number.

When there are more than 1 number in the same category (e.g. 2 number in Mobile category), this plugin will always return the first one.

After further test, I conclude that this plugin always return the first number registered for the selected  contact.  I found a case where one contact have Home number registered before Mobile number, and when I choose this contact, the plugin will always return Home number.

**Comment by hagaisela** [comment]
Hi,
This still happens to me on both android and IOS.
